### ISSUE TITLE
Bugsnag 5.0+ support

### ISSUE THREAD

**Issue by dmorrow** [segment-integrations/analytics-ios-integration-bugsnag#3]
Bugsnag 5.0 has been out since Feb - are there plans to support it?
https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v5.0.0

**Comment by dmorrow** [comment]
Is this project supported any longer?

**Comment by ladanazita** [comment]
Hi @dmorrow 
Sorry for the delay here.
I will open up a ticket to add this and update you here asap!

**Comment by joelmarquez90** [comment]
Hey @ladanazita please bump Bugsnag dependency since the [current supported version](https://github.com/segment-integrations/analytics-ios-integration-bugsnag/blob/master/Segment-Bugsnag.podspec#L25) doesn't have the [Session Tracking](https://docs.bugsnag.com/platforms/ios/#session-tracking) feature, among others.

Thanks!

**Comment by ladanazita** [comment]
@joelmarquez90 Hey there, sorry for the delay. Could you test out the branch I have above locally and let me know if that works for you? I haven't had time to end to end test — so testing this would help me get this shipped asap!

No worries if not, I will try to get to this later this week.

**Comment by ladanazita** [comment]
@joelmarquez90 @dmorrow this is live on version 1.0.3. I relaxed the Bugsnag dependency to 5.0, so running a pod update will pull in the latest up to but not including v6
